# -*- coding: utf-8 -*-
"""Tf-Idf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q37-qplStxhiw8W2xI_Bd1SDYilqueJD
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

df = pd.read_csv('/content/df_ar.csv')

df = df.dropna(subset=['text'])

tfidf_vectorizer = TfidfVectorizer(max_features=1000)

X_tfidf = tfidf_vectorizer.fit_transform(df['text'])

df_tfidf = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out())

print(df_tfidf.head())